# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
        - master
        - feature/*
  pull_request:
    branches: 
        - master
        - feature/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Pytest
      uses: cclauss/GitHub-Action-for-pytest@0.5.0
      with:
        args: pytest tests/test_*.py

    - name: Build and push docker
      uses: docker/build-push-action@v1.1.0
      with:
          repository: cerhard/carreratrack/carreratrack
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest,v0.0.1
          tag_with_ref: true
          dockerfile: Dockerfile
          
        


